### ISSUE TITLE
Kafka-connect is not removed from docker-compose

### ISSUE THREAD

**Issue by redrolla** [marco76/demo-sping-kafka#1]
Hello!
First of all big thanks for your tutorial and project.
But after cloning it and using "docker-compose up" I got error saing that container "kafka ui" cant start because it is dependant on  "kafka-connect", which is not existed.
So I removed "- kafka-connect0" from dependencies section of kafka-ui and it worked,
maybe you shoud remove it too in you project?

**Comment by marco76** [comment]
Hi Nick!

Many thanks for finding and pointing out the error! 👍 
I fixed it.

Thanks again!

😃
